version: '3.8'

services:
  frontend:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (optional if it's named "Dockerfile")
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 on the container
    environment:
      NODE_ENV: production  # Set environment variables for the container (if needed)
    volumes:
      - .:/app  # Bind mount the current directory to /app in the container (optional)
    restart: always  # Restart policy for the container
