name: SSH into Machine, Copy Repo, and Deploy
 
on:
  push:
    branches:
      - main  
 
jobs:
  ssh-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Install SSH Client and Rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync
 
    - name: SSH and Execute Commands on EC2
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" | ssh-agent sh -c '
          ssh-add - >/dev/null 
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-126-44-102.ap-south-1.compute.amazonaws.com << EOF
            sudo su -
            cd /home/ubuntu/hrms-devops/hrma-uat
            docker rmi -f hrms-backend-uat
            docker compose down
            cd hrms/HRMS-LMS\ App
            docker build -t hrms-backend-uat .
            docker images
            cd ../..
            docker compose up -d
          EOF
        '
      shell: bash
