name: SSH into Machine and Copy Repo

on:
  push:
    branches:
      - main  

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Client and Rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: SSH and Copy Repo to EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Create a temporary SSH key file
        echo "$SSH_KEY" > temp_ssh_key
        chmod 600 temp_ssh_key

        # Use rsync with the temporary SSH key file
        rsync -avz -e "ssh -i temp_ssh_key -o StrictHostKeyChecking=no" ./ ubuntu@ec2-13-126-44-102.ap-south-1.compute.amazonaws.com:/home/ubuntu/TEST/

        # Remove the temporary SSH key file
        rm temp_ssh_key

