name: SSH into Machine and Copy Repo

on:
  push:
    branches:
      - main  

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Client and Rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: Copy Repo to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ssh_key" ./ ubuntu@ec2-13-126-44-102.ap-south-1.compute.amazonaws.com:/home/ubuntu/TEST/

