name: SSH into Machine and Print Hello World

on:
  push:
    branches:
      - main  # You can change this to any branch you want

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: SSH and Print Hello World
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@ec2-13-126-44-102.ap-south-1.compute.amazonaws.com << 'EOF'
          echo "Connected successfully!"
          touch hello.world.txt
          ls -l hello.world.txt
        EOF
